//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cstate
    {
        public cstate()
        {
            this.customer = new HashSet<customer>();
            this.product = new HashSet<product>();
            this.tax = new HashSet<tax>();
            this.user = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<customer> customer { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<tax> tax { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
