//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctype_invoice
    {
        public ctype_invoice()
        {
            this.invoice = new HashSet<invoice>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<invoice> invoice { get; set; }
    }
}
