//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destado
    {
        public destado()
        {
            this.cmunicipio = new HashSet<cmunicipio>();
            this.customer = new HashSet<customer>();
        }
    
        public int iddEstado { get; set; }
        public string Nombre { get; set; }
        public string Pais { get; set; }
        public string Valor { get; set; }
        public byte Activo { get; set; }
    
        public virtual ICollection<cmunicipio> cmunicipio { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
