//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.customer = new HashSet<customer>();
            this.invoice = new HashSet<invoice>();
            this.product = new HashSet<product>();
            this.tax = new HashSet<tax>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string name { get; set; }
        public string fiscal_name { get; set; }
        public string rfc { get; set; }
        public string CodeTaxRegime { get; set; }
        public string PrivateCode { get; set; }
        public string UserPacFC { get; set; }
        public string PassPacFC { get; set; }
        public string cp { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual ICollection<customer> customer { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<tax> tax { get; set; }
    }
}
