//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_claveprodserv
    {
        public int id { get; set; }
        public string c_ClaveProdServ { get; set; }
        public string Descripcion { get; set; }
        public string Incluir_IVA_trasladado { get; set; }
        public string Incluir_IEPS_trasladado { get; set; }
        public string Complemento_que_debe_incluir { get; set; }
        public string FechaInicioVigencia { get; set; }
        public string FechaFinVigencia { get; set; }
        public string Palabras_similares { get; set; }
    }
}
