//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_patenteaduanal
    {
        public int id { get; set; }
        public string C_PatenteAduanal { get; set; }
        public string Inicio_de_vigencia { get; set; }
        public string Fin_de_vigencia { get; set; }
    }
}
