//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_regimenfiscal
    {
        public int id { get; set; }
        public string c_RegimenFiscal { get; set; }
        public string Descripcion { get; set; }
        public string Fisica { get; set; }
        public string Moral { get; set; }
        public string Fecha_de_inicio_de_vigencia { get; set; }
        public string Fecha_de_fin_de_vigencia { get; set; }
    }
}
