//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_impuesto
    {
        public int id { get; set; }
        public string c_Impuesto { get; set; }
        public string Descripcion { get; set; }
        public string Retencion { get; set; }
        public string Traslado { get; set; }
        public string Local_o_federal { get; set; }
        public string Entidad_en_la_que_aplica { get; set; }
    }
}
