//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_tipodecomprobante
    {
        public int id { get; set; }
        public string c_TipoDeComprobante { get; set; }
        public string Descripcion { get; set; }
        public string Valor_maximo { get; set; }
        public string D { get; set; }
        public string Fecha_inicio_de_vigencia { get; set; }
        public string Fecha_fin_de_vigencia { get; set; }
    }
}
