//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_pais
    {
        public int id { get; set; }
        public string c_Pais { get; set; }
        public string Descripcion { get; set; }
        public string Formato_de_codigo_postal { get; set; }
        public string Formato_de_Registro_de_Identidad_Tributaria { get; set; }
        public string Validacion_del_Registro_de_Identidad_Tributaria { get; set; }
        public string Agrupaciones { get; set; }
    }
}
